remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Prediction of role a player played in League of Legends competitive matches]
description: [by Orlando Fang (orlandofang0511@gmail.com)]
